import 'package:cached_network_image/cached_network_image.dart';
import 'package:cenafoodie/src/data/models/ui/ui_response.dart';
import 'package:cenafoodie/src/data/services/entities/category_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../data/models/entities/category/category.dart';
import '../../data/models/entities/delivery/delivery.dart';
import '../../data/models/entities/store/store.dart';
import '../../ui/blocs/delivery/delivery_bloc.dart';
import '../../ui/blocs/order/orders_bloc.dart';
import '../../ui/blocs/product/product_bloc.dart';
import '../../ui/resources/generated/l10n.dart';
import '../../ui/widgets/widgets.dart';
import '../configs/cena_colors.dart';
import '../image_ultils.dart';

part 'navigator_route_fade_in.dart';
part 'modal_loading.dart';
part 'modal_picture.dart';
part 'modal_success.dart';
part 'modal_selection_category.dart';
part 'modal_active_product.dart';
part 'modal_delete_product.dart';
part 'modal_select_delivery.dart';
part 'custom_markert.dart';
part 'modal_info.dart';
part 'url_lancher_cena.dart';
part 'modal_payment.dart';
part 'error_message.dart';
part 'modal_delete.dart';
part 'modal_delete_order.dart';
// part 'cena_convert.dart';
